version: "3.8"

services:
  api:
    container_name: videomanagement-api
    image: videomanagement
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    
    environment:
      SA_PASSWORD: "bhdKs3WOp7!"
      ACCEPT_EULA: "Y"
